'''
预付费缴费
'''
刷卡 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[1]/div[1]/div[1]/div/input'
姓名 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[2]/div[1]/div[1]/div/input'
费别 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[2]/div[1]/div[1]/div/input'
性别 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[3]/div[2]/div[1]/div/input'
余额 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[5]/div[1]/div[1]/div/input'
患者ID = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[1]/div[2]/div[1]/div/input'
生日 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[4]/div[2]/div[1]/div/input'
卡类型 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/div[5]/div[2]/div[1]/div'