# coding=utf-8
'''预付费退费(窗口)'''
缴费流水号 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[1]/div[1]/div[1]/div/input'
姓名 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[2]/div[1]/div[1]/div/input'
收款日期 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[3]/div[1]/div[1]/div/input'
科室 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[1]/div[2]/div[1]/div/input'
费用 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[2]/div[2]/div[1]/div/input'
费别 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[3]/div[2]/div[1]/div/input'
退费 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[5]/table[1]/tbody/tr[2]/td[2]/em/button'
清空 = '/html/body/div[1]/div/div[2]/div[1]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[1]/div[2]/div[1]/form/div/div/fieldset/div/div/div[5]/table[2]/tbody/tr[2]/td[2]/em/button'
